import { OrderItem, Order } from "../../redux";

const order1Items: Array<OrderItem> = ([
	{
		id: "juanita-order1-item1",
		type: "orderItems",
		attributes: {
			reason: null,
			completedAt: null,
			quantity: 2,
			lifecycleStatus: "IN_PROGRESS",
			inputtedCharacteristics: {},
			childOrderItems: [
				{
					id: "juanita-order1-item1-child-item1",
					name: "Appelsiini yPhone XS 32Gb white",
					customUnitPrices: [],
					customPrices: [],
					unitPrices: [],
					prices: [],
					quantity: 1,
					lifecycleStatus: "IN_PROGRESS",
					inputtedCharacteristics: {},
					completedAt: null,
					requestedCompletionDate: null,
					action: null,
					deliveryAddress: null,
					targetAgreementId: null,
					reason: null,
					childOrderItems: [
						{
							id: "juanita-order1-item1-child-item1-child-item1",
							name: "Appelsiini yPhone XS 32Gb white",
							customUnitPrices: [],
							customPrices: [],
							unitPrices: [],
							prices: [],
							quantity: 1,
							lifecycleStatus: "IN_PROGRESS",
							inputtedCharacteristics: {},
							completedAt: null,
							requestedCompletionDate: null,
							action: null,
							deliveryAddress: null,
							targetAgreementId: null,
							reason: null,
							childOrderItems: [],
							user: null,
						},
					],
					user: null,
				},
				{
					id: "juanita-order1-item1-child-item2",
					name: "Appelsiini yPhone XS 32Gb white",
					customUnitPrices: [],
					customPrices: [],
					unitPrices: [],
					prices: [],
					quantity: 1,
					lifecycleStatus: "IN_PROGRESS",
					inputtedCharacteristics: {},
					completedAt: null,
					requestedCompletionDate: null,
					action: null,
					deliveryAddress: null,
					targetAgreementId: null,
					reason: null,
					childOrderItems: [],
					user: null,
				},
			],
			customPrices: [],
			unitPrices: [],
			targetAgreementId: null,
			customUnitPrices: [],
			deliveryAddress: null,
			name: "Appelsiini yPhone XS 32Gb white",
			action: null,
			prices: [],
			user: null,
			requestedCompletionDate: null,
		},
		links: {
			self: "http://127.0.0.1:8080/omnichannel-api/api/v0/orderItems/juanita-order1-item1",
		},
	},
] as any) as Array<OrderItem>;
const order2Items: Array<OrderItem> = ([
	{
		id: "juanita-order2-item1",
		type: "orderItems",
		attributes: {
			reason: null,
			completedAt: null,
			quantity: 1,
			lifecycleStatus: "COMPLETED",
			inputtedCharacteristics: {},
			childOrderItems: [],
			customPrices: [],
			unitPrices: [],
			targetAgreementId: null,
			customUnitPrices: [],
			deliveryAddress: {
				role: null,
				id: "juanita-address",
				street: "89 Avenida Norte y Calle 11 Poniente",
				coAddress: "Edificio World Trade Center, Torre 2, Local 306, Colonia Escalón",
				postalCode: "01101",
				city: "San Salvador",
				country: "SV",
				county: null,
				description: null,
				postOfficeBox: null,
				stateOrProvince: "San Salvador",
			},
			name: "Prepaid SURF Plan",
			action: null,
			prices: [],
			user: {
				id: "juanita",
				customerAccountId: null,
				billingAccountId: null,
				firstName: "Juanita",
				lastName: "Solis",
				birthDay: "1990-04-13T00:00:00.000+0000",
				avatar: "/img/icon-user-female.svg",
				emails: [],
				mobileNumbers: [],
				fixedLineNumbers: [],
				postalAddresses: [],
				identifications: [],
				personRelationships: [],
				agreements: null,
				relatedPersons: null,
				orders: null,
				honorificPrefix: null,
				additionalName: "Maria",
				honorificSuffix: null,
				formattedName: "Juanita Solis",
				gender: "female",
				maritalStatus: "single",
				nationality: "SV",
				placeOfBirth: null,
				countryOfBirth: null,
				language: "spa",
				privacySettings: {},
				characteristics: null,
				password: null,
				register: null,
				baskets: null,
				transactionEvents: null,
				roles: null,
			},
			requestedCompletionDate: null,
		},
		links: {
			self: "http://127.0.0.1:8080/omnichannel-api/api/v0/orderItems/juanita-order2-item1",
		},
	},
	{
		id: "juanita-order2-item2",
		type: "orderItems",
		attributes: {
			reason: null,
			completedAt: null,
			quantity: 1,
			lifecycleStatus: "COMPLETED",
			inputtedCharacteristics: {},
			childOrderItems: [],
			customPrices: [],
			unitPrices: [
				{
					type: "RECURRENT",
					name: null,
					chargedUnit: {
						amount: 1,
						currency: null,
						unitOfMeasure: "PIECES",
					},
					taxAmount: null,
					taxFreeAmount: 14.45,
					taxRate: 0,
					recurringChargePeriod: { count: 1, interval: "MONTH" },
					currency: "EUR",
				},
			],
			targetAgreementId: null,
			customUnitPrices: [],
			deliveryAddress: null,
			name: "Data 21Mb/s",
			action: null,
			prices: [
				{
					type: "RECURRENT",
					name: null,
					chargedUnit: {
						amount: 1,
						currency: null,
						unitOfMeasure: "PIECES",
					},
					taxAmount: null,
					taxFreeAmount: 14.45,
					taxRate: 0,
					recurringChargePeriod: { count: 1, interval: "MONTH" },
					currency: "EUR",
				},
			],
			user: null,
			requestedCompletionDate: null,
		},
		links: {
			self: "http://127.0.0.1:8080/omnichannel-api/api/v0/orderItems/juanita-order2-item2",
		},
	},
] as any) as Array<OrderItem>;
const order3Items: Array<OrderItem> = ([
	{
		id: "juanita-order3-item1",
		type: "orderItems",
		attributes: {
			reason: null,
			completedAt: null,
			quantity: 1,
			lifecycleStatus: "COMPLETED",
			inputtedCharacteristics: {},
			childOrderItems: [],
			customPrices: [],
			unitPrices: [],
			targetAgreementId: null,
			customUnitPrices: [],
			deliveryAddress: {
				role: null,
				id: "juanita-address",
				street: "89 Avenida Norte y Calle 11 Poniente",
				coAddress: "Edificio World Trade Center, Torre 2, Local 306, Colonia Escalón",
				postalCode: "01101",
				city: "San Salvador",
				country: "SV",
				county: null,
				description: null,
				postOfficeBox: null,
				stateOrProvince: "San Salvador",
			},
			name: "Prepaid SURF Plan",
			action: null,
			prices: [],
			user: {
				id: "juanita",
				customerAccountId: null,
				billingAccountId: null,
				firstName: "Juanita",
				lastName: "Solis",
				birthDay: "1990-04-13T00:00:00.000+0000",
				avatar: "/img/icon-user-female.svg",
				emails: [],
				mobileNumbers: [],
				fixedLineNumbers: [],
				postalAddresses: [],
				identifications: [],
				personRelationships: [],
				agreements: null,
				relatedPersons: null,
				orders: null,
				honorificPrefix: null,
				additionalName: "Maria",
				honorificSuffix: null,
				formattedName: "Juanita Solis",
				gender: "female",
				maritalStatus: "single",
				nationality: "SV",
				placeOfBirth: null,
				countryOfBirth: null,
				language: "spa",
				privacySettings: {},
				characteristics: null,
				password: null,
				register: null,
				baskets: null,
				transactionEvents: null,
				roles: null,
			},
			requestedCompletionDate: null,
		},
		links: {
			self: "http://127.0.0.1:8080/omnichannel-api/api/v0/orderItems/juanita-order3-item1",
		},
	},
	{
		id: "juanita-order3-item2",
		type: "orderItems",
		attributes: {
			reason: null,
			completedAt: null,
			quantity: 1,
			lifecycleStatus: "COMPLETED",
			inputtedCharacteristics: {},
			childOrderItems: [],
			customPrices: [],
			unitPrices: [
				{
					type: "RECURRENT",
					name: null,
					chargedUnit: {
						amount: 1,
						currency: null,
						unitOfMeasure: "PIECES",
					},
					taxAmount: null,
					taxFreeAmount: 14.45,
					taxRate: 0,
					recurringChargePeriod: { count: 1, interval: "MONTH" },
					currency: "EUR",
				},
			],
			targetAgreementId: null,
			customUnitPrices: [],
			deliveryAddress: null,
			name: "Data 21Mb/s",
			action: null,
			prices: [
				{
					type: "RECURRENT",
					name: null,
					chargedUnit: {
						amount: 1,
						currency: null,
						unitOfMeasure: "PIECES",
					},
					taxAmount: null,
					taxFreeAmount: 14.45,
					taxRate: 0,
					recurringChargePeriod: { count: 1, interval: "MONTH" },
					currency: "EUR",
				},
			],
			user: null,
			requestedCompletionDate: null,
		},
		links: {
			self: "http://127.0.0.1:8080/omnichannel-api/api/v0/orderItems/juanita-order3-item2",
		},
	},
] as any) as Array<OrderItem>;
const order4Items: Array<OrderItem> = ([
	{
		id: "juanita-order4-item1",
		type: "orderItems",
		attributes: {
			reason: null,
			completedAt: null,
			quantity: 2,
			lifecycleStatus: "CANCELED",
			inputtedCharacteristics: {},
			childOrderItems: [],
			customPrices: [],
			unitPrices: [],
			targetAgreementId: null,
			customUnitPrices: [],
			deliveryAddress: null,
			name: "Zamzung Anarchy S5",
			action: null,
			prices: [],
			user: null,
			requestedCompletionDate: null,
		},
		links: {
			self: "http://127.0.0.1:8080/omnichannel-api/api/v0/orderItems/juanita-order4-item1",
		},
	},
] as any) as Array<OrderItem>;
const order5Items: Array<OrderItem> = ([
	{
		id: "juanita-order5-item1",
		type: "orderItems",
		attributes: {
			reason: null,
			completedAt: null,
			quantity: 1,
			lifecycleStatus: "ACKNOWLEDGED",
			inputtedCharacteristics: {},
			childOrderItems: [],
			customPrices: [],
			unitPrices: [],
			targetAgreementId: null,
			customUnitPrices: [],
			deliveryAddress: null,
			name: "OneMinus Two",
			action: null,
			prices: [],
			user: null,
			requestedCompletionDate: null,
		},
		links: {
			self: "http://127.0.0.1:8080/omnichannel-api/api/v0/orderItems/juanita-order5-item1",
		},
	},
	{
		id: "juanita-order5-item2",
		type: "orderItems",
		attributes: {
			reason: null,
			completedAt: null,
			quantity: 1,
			lifecycleStatus: "ACKNOWLEDGED",
			inputtedCharacteristics: {},
			childOrderItems: [],
			customPrices: [],
			unitPrices: [],
			targetAgreementId: null,
			customUnitPrices: [],
			deliveryAddress: null,
			name: "Music Steaming Service",
			action: null,
			prices: [],
			user: null,
			requestedCompletionDate: null,
		},
		links: {
			self: "http://127.0.0.1:8080/omnichannel-api/api/v0/orderItems/juanita-order5-item2",
		},
	},
	{
		id: "juanita-order5-item3",
		type: "orderItems",
		attributes: {
			reason: null,
			completedAt: null,
			quantity: 2,
			lifecycleStatus: "ACKNOWLEDGED",
			inputtedCharacteristics: {},
			childOrderItems: [],
			customPrices: [],
			unitPrices: [
				{
					type: "ONE_TIME",
					name: null,
					chargedUnit: {
						amount: 1,
						currency: null,
						unitOfMeasure: "PIECES",
					},
					taxAmount: null,
					taxFreeAmount: 39.95,
					taxRate: 0,
					recurringChargePeriod: null,
					currency: "EUR",
				},
			],
			targetAgreementId: null,
			customUnitPrices: [],
			deliveryAddress: null,
			name: "ZenHajzer SuperCool 32",
			action: null,
			prices: [
				{
					type: "ONE_TIME",
					name: null,
					chargedUnit: {
						amount: 1,
						currency: null,
						unitOfMeasure: "PIECES",
					},
					taxAmount: null,
					taxFreeAmount: 79.9,
					taxRate: 0,
					recurringChargePeriod: null,
					currency: "EUR",
				},
			],
			user: null,
			requestedCompletionDate: null,
		},
		links: {
			self: "http://127.0.0.1:8080/omnichannel-api/api/v0/orderItems/juanita-order5-item3",
		},
	},
] as any) as Array<OrderItem>;

const order: Order = ({
	id: "juanita-order1",
	type: "orders",
	attributes: {
		createdAt: "2017-10-03T09:21:40Z",
		price: null,
		changeable: false,
		salesInfo: {
			batchId: null,
			salesType: "MIGRATION",
			chainId: null,
			channel: "eCare",
			dealerId: null,
			salesPersonId: "p0774906",
		},
		ownerId: "juanita",
		status: "IN_PROGRESS",
		orderItems: order1Items,
	},
	relationships: {
		orderItems: {
			data: [{ id: "juanita-order1-item1", type: "orderItems" }],
			links: {
				self: "http://127.0.0.1:8080/omnichannel-api/api/v0/orders/juanita-order1/relationships/orderItems",
				related: "http://127.0.0.1:8080/omnichannel-api/api/v0/orders/juanita-order1/orderItems",
			},
		},
	},
} as any) as Order;

export { order };
