enum ProductLifecycleStatus {
	ACTIVE = "ACTIVE",
	COMPLETED = "COMPLETED",
	PENDING = "PENDING",
	TERMINATED = "TERMINATED",
	SUSPENDED = "SUSPENDED",
	INACTIVE = "INACTIVE",
	WAITING_FOR_ACTIVATION = "WAITING-FOR-ACTIVATION"
}

export {
	ProductLifecycleStatus
};
