enum SpecSubTypeEnum {
	HANDSET = "HANDSET",
	TABLET = "TABLET",
	ACCESSORY = "ACCESSORY",
	MODEM = "MODEM",
	SIM = "SIM",
	MSISDN = "MSISDN",
	VOICE = "VOICE",
	DATA = "DATA",
	SMS = "SMS",
	MMS = "MMS",
	ADDITIONAL = "ADDITIONAL",
	ENTERTAINMENT = "ENTERTAINMENT",
	SECURITY = "SECURITY",
	MOBILE = "MOBILE",
	FIXED_LINE = "FIXED_LINE",
	BROADBAND = "BROADBAND",
	TV = "TV",
	SERVICE = "SERVICE",
	RESOURCE = "RESOURCE",
	SERVICE_REQUEST = "SERVICE_REQUEST",
	BLOCKING = "BLOCKING",
	SUBSCRIPTION = "SUBSCRIPTION"
}

type SpecSubType = keyof typeof SpecSubTypeEnum;

export {
	SpecSubTypeEnum,
	SpecSubType
};
