enum UnitOfMeasureEnum {
	SMS = "SMS",
	MMS = "MMS",
	MONETARY = "MONETARY",
	PIECES = "PIECES",
	DOZENS = "DOZENS",
	PERCENTS = "PERCENTS",
	PERMILLES = "PERMILLES",
	BASISPOINTS = "BASISPOINTS",
	BITS = "BITS",
	BYTES = "BYTES",
	KILOBYTES = "KILOBYTES",
	MEGABYTES = "MEGABYTES",
	GIGABYTES = "GIGABYTES",
	TERABYTES = "TERABYTES",
	KIBIBYTES = "KIBIBYTES",
	GIBIBYTES = "GIBIBYTES",
	TEBIBYTES = "TEBIBYTES",
	PEBIBYTES = "PEBIBYTES",
	PETABYTES = "PETABYTES",
	MEBIBYTES = "MEBIBYTES",
	SECONDS = "SECONDS",
	MINUTES = "MINUTES",
	HOURS = "HOURS",
	DAYS = "DAYS",
	WEEKS = "WEEKS",
	MONTHS = "MONTHS",
	SERVICE_SPECIFIC = "SERVICE_SPECIFIC",
}

type UnitOfMeasureType = keyof typeof UnitOfMeasureEnum;

export {
	UnitOfMeasureType,
	UnitOfMeasureEnum
};
