enum CommonCustomizationPoints {
	TEST_COMPONENT = "TEST_COMPONENT",
	CMS_COMPONENT = "CMS_COMPONENT",
	CMS_PREVIEW_CONTENT = "CMS_PREVIEW_CONTENT",
	CMS_ASSET_LIBRARY = "CMS_ASSET_LIBRARY",
	LANGS_SELECTOR = "COMMON_LANGS_SELECTOR",
	TARIFF_PLANS = "TARIFF_PLANS",
	ADDON_TAB_TABLE_HEADER = "ADDON_TAB_TABLE_HEADER",
	ADDON_ROW = "ADDON_ROW",
	SERVICE_ROW = "SERVICE_ROW",
	CALL_FORWARDING_ROW = "CALL_FORWARDING_ROW",
	PRODUCT_LOAN_ROW = "PRODUCT_LOAN_ROW",
	STATE_CHANGE_MODAL = "STATE_CHANGE_MODAL",
	ADDON_STATE_CHANGE_MODAL = "ADDON_STATE_CHANGE_MODAL",
	SERVICE_STATE_CHANGE_MODAL = "SERVICE_STATE_CHANGE_MODAL",
	ADDRESS_VALIDATION_HANDLER_CONTAINER = "ADDRESS_VALIDATION_HANDLER_CONTAINER",
	ADDRESS_VALIDATION_HANDLER_PROPOSALS = "ADDRESS_VALIDATION_HANDLER_PROPOSALS",
	PLAN_LIST_ROW = "PLAN_LIST_ROW",
	PLAN_LIST_ROW_HEADERS = "PLAN_LIST_ROW_HEADERS",
	ADDONS_TAB_CONTENT = "ADDONS_TAB_CONTENT",
	ADDONS_LIST_CONTENT = "ADDONS_LIST_CONTENT",
	PRODUCT_LOANS_LIST_CONTENT = "PRODUCT_LOANS_LIST_CONTENT",
	SERVICES_LIST_CONTENT = "SERVICES_LIST_CONTENT",
	USAGE_DONUT = "USAGE_DONUT",
	CHECKABLE_ADDON_COMPONENT = "CHECKABLE_ADDON_COMPONENT",
	CHECKABLE_ADDON_MODAL_COMPONENT = "CHECKABLE_ADDON_MODAL_COMPONENT",
	ERROR_MODAL_CONTENTS_MESSAGE_INJECTOR = "ERROR_MODAL_CONTENTS_MESSAGE_INJECTOR",
	BASKET_POPUP_FOOTER_ACTIONS = "BASKET_POPUP_FOOTER_ACTIONS",
	RECURRING_TOPUP_AMOUNT = "RECURRING_TOPUP_AMOUNT",
	ACTIVATE_SIM_MODAL = "ACTIVATE_SIM_MODAL",
}

enum UtilsCustomizationPoints {
	SCHEMA_UTILS = "SCHEMA_UTILS",
	SCHEMA_UTILS_VALIDATE_EXTRA_PROPERTIES = "SCHEMA_UTILS_VALIDATE_EXTRA_PROPERTIES",
	POSTAL_ADDRESS_UTIL_GET_ADDRESS_FOR_MESSAGE = "POSTAL_ADDRESS_UTIL_GET_ADDRESS_FOR_MESSAGE",
	POSTAL_ADDRESS_UTIL_GET_ADDRESS_AS_STRING = "POSTAL_ADDRESS_UTIL_GET_ADDRESS_AS_STRING",
	POSTAL_ADDRESS_UTIL_GET_DELIVERY_ADDRESS_PARTS = "POSTAL_ADDRESS_UTIL_GET_DELIVERY_ADDRESS_PARTS",
	POSTAL_ADDRESS_UTIL_TOKENIZE_STREET_ADDRESS = "POSTAL_ADDRESS_UTIL_TOKENIZE_STREET_ADDRESS",
	GET_MSISDN_WITH_SEPARATED_AREA_CODE = "GET_MSISDN_WITH_SEPARATED_AREA_CODE",
}

enum CommonSchemaCustomizationPoints {
	DELIVERY_ADDRESS = "DELIVERY_ADDRESS",
}

enum CommonFunctionCustomizationPoints {
	DOMAIN_CONTEXT_KEY_MAPPER = "DOMAIN_CONTEXT_KEY_MAPPER",
	DOWNLOAD_DOCUMENT = "DOWNLOAD_DOCUMENT",
	MSISDN_SELECTION_HANDLE_PATTERN = "MSISDN_SELECTION_HANDLE_PATTERN",
	ADD_PRODUCT_TO_BASKET_ITEM = "ADD_PRODUCT_TO_BASKET_ITEM",
}

export {
	CommonCustomizationPoints,
	UtilsCustomizationPoints,
	CommonSchemaCustomizationPoints,
	CommonFunctionCustomizationPoints
};
