enum POSComponentCustomizationPoints {
	APP_ROUTES_EXTENSION = "POS_APP_ROUTES_EXTENSION",
	INSTALLATION_ADDRESS_SEARCH_FORM = " INSTALLATION_ADDRESS_SEARCH_FORM",
	INSTALLATION_ADDRESS_SEARCH_FORM_CONTAINER = " INSTALLATION_ADDRESS_SEARCH_FORM_CONTAINER",
	POS_MSISDN_CONFIGURATION_MODAL = "POS_MSISDN_CONFIGURATION_MODAL",
	POS_CUSTOMER_DATA_FORM_CONTAINER = "POS_CUSTOMER_DATA_FORM_CONTAINER",
	POS_CUSTOMER_DETAILS_CONTAINER = "POS_CUSTOMER_DETAILS_CONTAINER",
	POS_PERSON_DETAILS_FORM = "POS_PERSON_DETAILS_FORM"
}

enum POSFunctionCustomizationPoints {
	RENDER_CHARACTERISTICS_INPUT_ELEMENT = "RENDER_CHARACTERISTICS_INPUT_ELEMENT",
	RENDER_BASKET_MINI_BASKET_ERROR = "RENDER_MINI_BASKET_ERROR",
}

enum POSSchemaCustomizationPoints {
	MSISDN_TRANSFER = "MSISDN_TRANSFER",
}

export {
	POSComponentCustomizationPoints,
	POSFunctionCustomizationPoints,
	POSSchemaCustomizationPoints
};
